### PR TITLE
[VA-4418] Add qoe error field to xdm

### PR DESCRIPTION
**Pull request by lidiaist**
Issue https://github.com/adobe/xdm/issues/700

### CODE REVIEW

**Comment by lidiaist** [comment]
@prabhum2 @mjasrotia  Please review and let me know if I need to make any changes. These changes add support for qoe custom error details (errorID and errorSource). Thank you!

**Review by mjasrotia — APPROVED** [review]

**Comment by prabhum2** [comment]
@lidiaist Please let us know if more changes expected in this PR or ready to be reviewed and merged ?

**Comment by lidiaist** [comment]
@prabhum2 we might still need to add more changes but it is an ongoing investigation, this PR can also be merged as it is right now. Thank you!

**Comment by prabhum2** [comment]
@lidiaist . Please let me know if you/your team incorporated required changes ? I will for now put this in draft mode

**Comment by lidiaist** [comment]
@prabhum2 we decided we don't need any more additional changes, only the current PR needs to be merged. Thank you!

**Pull request merged**
