### PR TITLE
Add address and person related schemas to common

### PR DESCRIPTION
**Pull request by jwen-adobe**
@kstreete @trieloff @cmathis

1. Add address to common folder.
2. Move person related schemas to common folder.

Link to the issue #74, #63, #64.

### CODE REVIEW

**Comment by trieloff** [comment]
For `auditable`, we already have PR #69, which depends on #73.

**Comment by jwen-adobe** [comment]
@trieloff ok, will modify once PR #69 goes in as address and person reference it.

**Comment by jwen-adobe** [comment]
@trieloff I also saw that u have made bunch of changes in the experience-cloud-staging. Do u still need me to create smaller PRs like five schemas a time, or u will just merge the ones u feel good from staging directly to master?

**Comment by trieloff** [comment]
Hi @jwen-adobe my plan was to merge folder-by-folder. Most dependencies rest on `common` that's why I started here (and also made sure that things that are not really common move out of it).

The things that I can solve myself, I'm fixing myself, for all other questions I'm raising issues. Once we have most of `common` merged, we can divide and conquer to create a bunch of PRs.

I want all of these merges (including my own) go through PRs, so that there is a chance to look over it.

**Comment by jwen-adobe** [comment]
Close this and will open new PR for new schemas into common folder.

**Pull request closed without merging**
