### PR TITLE
Segment definition and Segment folder to have identity in identity map

### PR DESCRIPTION
**Pull request by ankushkd**
New Audience Manager extension specific segment folder schema added.
Segment definition and segment folder will use identityMap to pass primary identity.

### CODE REVIEW

**Comment by cmathis** [comment]
On the new SegmentFolder object, is the segmentParentFolderIdentity field expected to be processed by UPS or would they only care about the identityMap value(s)?

**Comment by ankushkd** [comment]
@cmathis  this will only work with identityMap and need not work with segmentParentFolderIdentity.

**Comment by cmathis** [comment]
@ankushkd  - If the Identity Service makes a change where they automatically consume any field of type "context/identity", will that be a problem? I don't think that logic is in place today, but may be part of their future roadmap.

**Comment by ankushkd** [comment]
@cmathis  Thats true. How can we handle this? We need folder identity here to tell which folder this segment belongs to.

**Comment by cmathis** [comment]
Is this "folder identity" associated with the core identity service at all?  The current context/identity is intended to represent an identity from that core service. If they are not associated, we should look into representing the folder identity in a different way.

**Comment by ankushkd** [comment]
no, its not to be used by identity service for this schema, its just reference to identity in identity map of segment folder schema. Since its a reference, structure of id and namespace required.

**Comment by cmathis** [comment]
I hate to see up duplicating too much, but we may be safer to have a new context/identityReference object which can be used for this. It can be much smaller that the current context/identity and only those fields needed in this case.

The description would be something along the lines of: "Identity information that is not intended to be the identity of **this** schema, but used to reference the identity of another schema.

cc @prabhum2 and Vikas to agree or disagree with this approach.

**Comment by ankushkd** [comment]
@cmathis  Is using Segment Identity https://github.com/adobe/xdm/blob/master/schemas/context/segmentidentity.schema.json an option?

**Comment by cmathis** [comment]
@ankushkd  - Yes, that should work. Anything that the Identity Service would not be watching for and treating as the identity.

**Comment by cmathis** [comment]
As part of the PR we are introducing a new context/identityReference data type to avoid any confusion with the current context/identity. This new data type is used when you want the field to reference the identity field of a foreign schema/object. This along with the existing relationshipIdentity descriptor would allow for the following within XDM.

1. A field can be defined as a string and use the referenceIdentity descriptor to assign the associated foreign namespace 
2. A field can be defined as an identityReference where the namespace is supplied in the ingested data

**Comment by ktukker** [comment]
Hello Craig, team, The PR as provided with "context/referenceIdentity" is fine by me. We should clean this up in future by looking at this holistically.

**Comment by cmathis** [comment]
retest

**Comment by cmathis** [comment]
Have updated the PR to introduce a new boolean refefenceIdentity attribute on the context/identity datatype. This attribute is set to true when the field is referring to the identity of a foreign entity, and should **NOT** be be consumed by Identity Service as one of its own identifiers. 

cc Vikas and Srini

**Comment by cmathis** [comment]
@khanna-vikas and @smcodes please take a look at this and approve. Was decided that because UIS will not process non-person identities, the introduction of a new flag is not necessary at the moment. This will give UIS some time to process this proposal of new flag, or come up with a better alternative.

**Pull request merged**
