### PR TITLE
Definition of descriptor for search annotations

### PR DESCRIPTION
**Pull request by nandaja**
This links to Issue 489 - https://github.com/adobe/xdm/issues/489

This PR defines a XDM descriptor for search annotations. Details in the issue. 

Changes here comply to the proposal on : https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=adobesearch&title=Search+annotations+in+XDM+-+Proposal

@ogoldman  @lrosenthol  @kstreeter @jaganperi

### CODE REVIEW

**Comment by kstreeter** [comment]
Hi @nandaja, @ogoldman is this PR ready to go?

**Comment by nandaja** [comment]
@kstreeter  This PR is good to go, as long as the reviews are complete. I have resolved conflicts. Are there any next steps before merge ?

**Comment by ogoldman** [comment]
@kstreeter Yes, good to go

**Comment by nandaja** [comment]
Thanks @ogoldman  and @kstreeter

**Pull request merged**
