### PR TITLE
JSON HAL External Schema

### PR DESCRIPTION
**Pull request by trieloff**
PR for #28, allowing us to express relationships between resources in a more standardized way (and the same way the Adobe Cloud Platform is prescribing)

### CODE REVIEW

**Comment by fmeschbe** [comment]
See also https://git.corp.adobe.com/pages/experience-platform/api-guidelines/6-json-standardizations.html#links

I wonder, whether it is a stable assumption to refer to and re-use an expired and archived draft ? Maybe we should just define our own `_links` specification (as down in above API guidelines) ?

**Comment by lucianfelix** [comment]
Could you also add an example with ```_embedded```? It's interesting as it has implications on collection resources.

**Comment by trieloff** [comment]
The link above is basically a subset of HAL, with the added disadvantage that we don't call it HAL, and that users won't get the idea of using things like https://github.com/mikekelly/hal_specification/wiki/Libraries that are compatible with it, whether we call it this or not.

**Comment by trieloff** [comment]
@lucianfelix – I could, but I just noticed that the `_embedded` schema is too restrictive.

**Comment by fmeschbe** [comment]
> The link above is basically a subset of HAL

@trieloff yes, it is derived from the API spec with some added properties.

In any case, that was just a reference. The main point is whether we want to actually refer to a defunct draft or whether it would be better to refer to the actual spec https://github.com/mikekelly/hal_specification (which also has not been updated in a long time) and work with the author to come up with a proper schema.

I am not feeling very confident with defining a JSON Schema in a foreign URL space.

**Comment by trieloff** [comment]
Regarding the HAL status: https://groups.google.com/forum/#!topic/hal-discuss/WrI5YDQo610 (tl;dr: not dead)

There are a number of schemas for HAL already. I did not copy any of them for following reasons:

1. either they don't have a license
2. or the license is not CC (e.g. https://github.com/DaveJS/dave.schema.json is MPL)
3. and the schema not structured in a way that works well with our documentation

We have created JSON Schemas for a number of other standards, without implying that this JSON Schema would have a reach beyond XDM, so I'd assume to treat HAL the same.

**Comment by trieloff** [comment]
Comment from @fmeschbe via Slack:

> was mich dann nur noch stört ist die ID, welche Du einem non-Adobe namespace hast…

> The only remaining thing I object to is that your `$id` points to a non-Adobe Namespace, although we only interpret HAL and don't use any official schema.

**Pull request closed without merging**
