### PR TITLE
Rearrange analytics extension fields to use nested structure

### PR DESCRIPTION
**Pull request by kstreeter**
This PR moves the Analytics extension fields into nested objects, versus having them organized with distinct namespaces.

Please link to the issue #…

This is one of the issues described in #277.

### CODE REVIEW

**Comment by kstreeter** [comment]
@cmathis, @jwen-adobe can you check this out and make sure it continues to work with our tooling?

**Comment by jwen-adobe** [comment]
@kstreeter It works well with the tooling.

**Comment by cdegroot-adobe** [comment]
Looking at this, one aspect we are realizing is that extensions should generally be organized into grouping fields in the hierarchy rather then over populating the root nodes of the schemas they are extending.

**Comment by cmathis** [comment]
We should do this same thing to https://github.com/adobe/xdm/pull/302.

**Pull request merged**
