### PR TITLE
[AMO-131288] - Added Schema Definitions for Ad Cloud Search MetaData

### PR DESCRIPTION
**Pull request by jishah-adobe**
Please link to the issue #…

### CODE REVIEW

**Comment by jishah-adobe** [comment]
@ktukker @ktukker-adobe @prabhum2 @cmathis @cfraser

**Comment by cmathis** [comment]
We've gone through these before so there is not a lot to review. 

@ktukker and @cfraser  - This will introduce 8 new global classes that will show up along side the current XDM Profile and XDM ExperienceEvent. These will appear for every tenant. Waiting for your confirmation and approval before we merge this in.

**Comment by sathyz** [comment]
## Campaigns, Accounts
Are we expecting each Adobe Marketing Solutions (Adobe Campaign, CMP, DSP and Search) create their version of campaign and accounts? We should have one generic version of campaign that fits all solutions (like campaign id, name, goal, budget, spend strategy etc). 

In aggregateperformancebykeyword.schema.json, do we need to add attributes like campaignId, keywordId, termId, accountId. when they are already defined in adcloud/campaign.schema.json. 

## Match type
When we worked on publishing experience events for AdCloud (Search) we have added matchType to AdCloud's Campaign, we now have matchType in aggregateperformancebyadbykeyword.schema.json  & aggregateperformancebykeyword.schema.json and we had defined enums all in small cases and here it in capital cases (broad vs Broad). This will create a state of disjoint. Match Types enum should be defined in one place and other schemas should use it same as how we are doing for device.

**Comment by jishah-adobe** [comment]
> ## Campaigns, Accounts
> Are we expecting each Adobe Marketing Solutions (Adobe Campaign, CMP, DSP and Search) create their version of campaign and accounts? We should have one generic version of campaign that fits all solutions (like campaign id, name, goal, budget, spend strategy etc).
> 
> In aggregateperformancebykeyword.schema.json, do we need to add attributes like campaignId, keywordId, termId, accountId. when they are already defined in adcloud/campaign.schema.json.
> 
> ## Match type
> When we worked on publishing experience events for AdCloud (Search) we have added matchType to AdCloud's Campaign, we now have matchType in aggregateperformancebyadbykeyword.schema.json & aggregateperformancebykeyword.schema.json and we had defined enums all in small cases and here it in capital cases (broad vs Broad). This will create a state of disjoint. Match Types enum should be defined in one place and other schemas should use it same as how we are doing for device.

Yes each Adobe solution (Search, DSP, Social) are expected to define their own version of campaign. The definition and semantic of campaign is different for each of these solutions hence different schema. Unfortunately there can be no single version of campaign that fits all solutions.  In fact during the exercise we noticed that search partners (Google, Yahoo, Bing) also have different flavors of campaign definition.  We also started with creating mix-ins and data-types but unfortunately that didn't fit well with XDM semantics.  We were recommended to create class for each entity and define fields within the class for that entity (e.g campaign, ad group and so on).  As far as adcloud/campaign.schema.json is concerned, the schema should not have been called as campaign in first place. It is is just a hierarchy of ID's. 

As far as match types are concerned, I believe it is an attribute of a keyword and should be associated with keywords only.  I agree on part of case sensitivity.  We need to decide on who bears the responsibility of case conversions - Readers of the data (query time) or writers of the data (ingestion time).  On a second thought, I am also rethinking on defining hard enumerations.  I will discuss them with XDM team and adjust schemas based on the guidance.

**Comment by cmathis** [comment]
I have a hard time believing there are no common fields between the different instances of a Campaign no matter what solution it is for. I would expect every Campaign to have an ID, name, and description at least. I created the following PR as an alternative approach to give an example of how this could work  - https://github.com/adobe/xdm/pull/705

This same concept could be used to create a generic Account and solution specific mixins for that as well. 

I will let @ktukker @cfraser  and Srini decide what is the best approach for AEP.

**Comment by lohariwa-adobe** [comment]
> I have a hard time believing there are no common fields between the different instances of a Campaign no matter what solution it is for. I would expect every Campaign to have an ID, name, and description at least. I created the following PR as an alternative approach to give an example of how this could work - #705

@cmathis @ktukker @sathyz: I would say that such a "Campaign" would be a _mixin_ and not a parent class. This is because it won't be a clear real world parent representation of search campaigns and demand-side-platform (DSP) campaigns together. A user of DSP will take it to mean one thing which would not hold true for Search Advertising and vice-versa. I would recommend that we should not attempt to merge these concepts just because they are both under the AdCloud umbrella. If we want to model these concepts in a user/persona Experience driven way, it will be best to represent them clearly in separate namespaces. This will allow marketers and advertisers to look at objects created using such schema in the correct context and make sense of them.

**Comment by jwen-adobe** [comment]
@jishah-adobe need to get Adobe CLA Signed for passing the check.

**Comment by ktukker-adobe** [comment]
After meeting with the AdCloud team, Srinivas and I support this PR. Additional context on the naming of the entities (namespace in the adcloud/searchadvertising):

In the Search Advertising domain:

Campaign: Definition
A set of ad groups (ads, keywords, and bids) that share a budget, location targeting, and other settings. Campaigns are often used to organize categories of products or services that you offer.
•	Advertising Search account can have one or many ad campaigns running.
•	Each campaign consists of one or more ad groups.
•	Settings that you can set at the campaign level include budget, language, location, distribution for the Network, and more.
•	You can create separate ad campaigns to run ads in different locations or using different budgets.

In the Display advertising domain:

Display Placement: Definition
A set of parameters for a specific video ad or set of video ads or  Image ads that define where and when the ads should run. You can create unlimited placements for each campaign. Placement have Ads Units and Budgets and Targeting criteria (Geo, Inventory, Site, Audience

**Comment by ktukker-adobe** [comment]
@kstreeter , @prabhum2 can you merge this PR?

**Comment by udayeyunni** [comment]
@prabhum2 / @kstreeter - Can this PR be merged this week? Do you need anything else from us before you merge the PR?

**Pull request merged**
