### PR TITLE
Issue 595 - Moving segment membership from array to map

### PR DESCRIPTION
**Pull request by kstreeter**
Addresses issue #595.  This PR supercedes #593.

### CODE REVIEW

**Comment by kstreeter** [comment]
The structure in this PR is basically the same as the one proposed in #593, but re-uses the original mixins so that the definitions are properly pulled into all of the solution extensions.  I also added the (optional) profile stitch ID to the map item, so that profile and experienceevent now have matching definitions for segment membership.

**Comment by meetraviagg** [comment]
@kstreeter since we are changing existing definitions, will this be released as new xdm version. Because if xdm version is not changing wont it break the existing clients who are still expecting segment-array instead of segment-map ?

**Comment by kstreeter** [comment]
Hi @meetraviagg yes this is a breaking change, but we have a number of those planned for 09.9 as we address issues based on feedback from users.

**Comment by meetraviagg** [comment]
Hi @kstreeter, so will it be released as xdm version 0.9.9.9 itself ??
If that will be the case, it will be a problem for us.
@rkpandey - please confirm ...

**Comment by meetraviagg** [comment]
Hi @kstreeter i talked to Raghav, and we are ok if these changes are going in 0.9.9.9.
But i am hoping that before any deployment happens, the timelines for that will be synced with profile team, so that clients are not affected. Thanks.
cc @rkpandey

**Comment by kstreeter** [comment]
Okay, this one is in.  Note that after some discussion with @cdegroot-adobe we decided to keep the original definitions temporarily to give folks a chance to absorb the change.

**Pull request merged**
