### PR TITLE
Issue 419 - changing Identity id from URI format to plain string

### PR DESCRIPTION
**Pull request by kstreeter**
This PR is to address issue #419, where the definition of `@id` in the `Identity` schema is too constrained for real usage.  This PR changes the field from `@id` to `xdm:id`, and updates all of the examples.

### CODE REVIEW

**Comment by jwen-adobe** [comment]
@kstreeter This looks good from tooling perspective based on my test.

**Comment by cdegroot-adobe** [comment]
Technically this PR does remove the need for URIs, but the examples still are URIs.

What is the reason we are not using URL encoding? The cases where there are non URL safe characters is a corner case.

**Comment by saurabhere** [comment]
Looks good. So, `_id` becomes `id` in XED for identities. Hope this is communicated to all the consumers(UPS, siphon)

**Comment by saurabhere** [comment]
Can this also include similar changes in the `orgunit.schema` and `geounit.schema` ?

**Comment by cdegroot-adobe** [comment]
@saurabhere this change is limited to the Identity schema. The standard in XDM is to use @id for the globally unique identifier of all entities.

**Comment by cdegroot-adobe** [comment]
@fmeschbe - we need to include this in the July 16th milestone.

**Pull request merged**
