### PR TITLE
changing the datatype namespace to xdm

### PR DESCRIPTION
**Pull request by shagreel**
When viewing the previous xdm change in the stage env I discovered that a datatype needs to use the `xdm` namespace otherwise the namespace is prepended to the datatype fields. I have made this change. If this merge could be added to last week's release that would be best so we do not introduce an invalid datatype in the prod env.

### CODE REVIEW

**Review by donwalling — APPROVED** [review]
+1

**Comment by shagreel** [comment]
This is a known breaking change. No one is using the schema that this is changing.

**Comment by shagreel** [comment]
This PR is ready for deployment.

**Comment by mjasrotia** [comment]
Approving this after discussion with @shagreel that these properties are not yet used anywhere.

**Pull request merged**
