### PR TITLE
Adds title for page views and link clicks

### PR DESCRIPTION
**Pull request by dancingcactus**
Adds a human readable title to the metrics in webPageDetails and WebInteractionDetails.

### CODE REVIEW

**Comment by lrosenthol** [comment]
@dancingcactus how does this get used?  can you post an example or update existing ones?

**Comment by dancingcactus** [comment]
@lrosenthol Thanks for taking a look at this. I am a bit new to contributing to XDM. This is just adding a human readable title to schemas that already exist. As I looked at the examples I didn't see anywhere the title was used. What am I missing?

**Comment by lrosenthol** [comment]
Ah - sorry.  Misread what you were doing.  

Perfectly fine work then.  I'll approve.

**Comment by dancingcactus** [comment]
I am going to close this since my Adobe CLA Signed didn't go through.

**Pull request closed without merging**
