### PR TITLE
1017 card comparison mixin and comparison data type

### PR DESCRIPTION
**Pull request by jbranson000**
https://github.com/adobe/xdm/issues/1017

### CODE REVIEW

**Comment by cmathis** [comment]
@jbranson000  - Is this new datatype ever to be used outside of the context of this new "cardComparisonDetails" field? If not, then let's define those field directly under the field its self or as a local definition you reference. Let's not clutter AEP with new datatypes that have no reusability.

**Comment by cmathis** [comment]
What is a "Card" in this case and how are they related to ExperienceEvent datasets?

**Comment by jbranson000** [comment]
@cmathis A "card" could be any type of credit, debit, HSA, FSA, Prepaid, etc.  Most of the mixins we are creating are part of the ExperienceEvent datasets.

**Comment by cmathis** [comment]
@jbranson000 - A potential issue here is that you are wanting to introduce this "xdm:cardComparisonDetails" as a new root level field. In ExperienceEvent data root level fields are generally a high level category which contains fields under it related to that category. I'm assuming this "cardComparisonDetails" would be associated with other banking related fields. What could be the high level category associated with these fields? Once you have that you could do something like:

`      
"properties": {
     "xdm:consumerBanking": { //Or whatever you think this should be
       "type": "object",
       "properties": {
            "xdm:cardComparisonDetails ": {
                "title": "Card Comparison Details",
                "$ref": "https://ns.adobe.com/xdm/datatypes/comparisons",
                "description": "Card comparison details such as count, addition, removal, and view."
             }
       }
}
`

**Comment by jbranson000** [comment]
This datatype and mixin is being merged into 1018 - thus this can be closed.

**Pull request closed without merging**
