### PR TITLE
Camel case for #23

### PR DESCRIPTION
**Pull request by trieloff**
Here are the changes to implement #23

### CODE REVIEW

**Comment by trieloff** [comment]
@lrosenthol please take a look, too

**Comment by lrosenthol** [comment]
Looks good to me, @trieloff  - thanks for all the hard work on these edits!

**Comment by trieloff** [comment]
@lrosenthol we might want to have another look at some of the XMP properties. If I remember correctly, some start with capital letters, which is not according to style guide, but for consistency's sake I'd follow XMP's lead for properties where XMP has been inconsistent. WDYT?

**Comment by lrosenthol** [comment]
yes, I saw a few of those (eg. ICCProfile) while reviewing, but we definitely want to keep them compatible with XMP (or any other existing schema we are taking from)

**Comment by trieloff** [comment]
ICCProfile rolls just off the tongue, but dmaID isn't bad either ;)

**Pull request merged**
