### PR TITLE
Add search descriptors to identity schema

### PR DESCRIPTION
**Pull request by adipan**
In identity schema, I am adding search descriptors as they are required for search integration. This is required in collaboration scenarios where a user Alice may wish to search for assets created by user Bob with user id as uidOfBob.

Please link to the issue #…

### CODE REVIEW

**Comment by adipan** [comment]
Closed back on feedback from Oliver. I would wait for PAPI discussion to conclude.

**Comment by adipan** [comment]
Removing any changes to principal schema since PAPI WG is taking care of that.

**Comment by prabhum2** [comment]
i know nothing about use cases of this schema . Can another reviewer from this side of the business review and let us know if this makes sense

**Comment by adipan** [comment]
Closing this PR, in favor of https://git.corp.adobe.com/AdobeCloudPlatform/api-spec/pull/220

**Pull request closed without merging**
