### PR TITLE
[545] New model for auxiliaryProperties added. Map of String and values

### PR DESCRIPTION
**Pull request by ankushkd**
Issue: https://github.com/adobe/xdm/issues/545

### CODE REVIEW

**Comment by lrosenthol** [comment]
We already have a way to do this with XDM - please don't create your own.   @kstreeter can you help here?

**Comment by ankushkd** [comment]
@kstreeter  @lrosenthol  please advise here. We want to be able to define and validate type of value in map.

**Comment by lrosenthol** [comment]
@ankushkd My biggest problem with this approach is shown perfectly in your example - you have numbers represented as strings, which we would not want.  Data needs to be properly typed.

**Comment by ankushkd** [comment]
@lrosenthol The example could be better here, will update. Important point is, it is meant for keys we do not know yet. And these are not always fixed as well. We can not model it on the fly and  even if we try to it, it would end up as huge horizontal schema. Requirement is to model this not currently known key value pairs which are coming though ingestion channels into a Map. Downstream systems and validation services will need to know the value type is a String array.

**Comment by ankushkd** [comment]
Closing this pull request. Will open a new one with latest changes.

**Comment by ankushkd** [comment]
Please refer to https://github.com/adobe/xdm/pull/556 for latest on this.

**Pull request closed without merging**
