### PR TITLE
Correcting Extensibility statements in `context` schemas

### PR DESCRIPTION
**Pull request by cdegroot-adobe**
- Added `"meta:extends": true` to the schemas that can be extended in `context`

Oversight during previous authoring

### CODE REVIEW

**Comment by cdegroot-adobe** [comment]
@kstreeter  - Required for Analytics Beta.

**Comment by kstreeter** [comment]
Hi @cdegroot-adobe, just a reminder that in addition to "meta:extensible" these also need to mix-in the extensibility context.

**Comment by kstreeter** [comment]
@cdegroot-adobe can we have this in the June 15th release?

**Comment by cdegroot-adobe** [comment]
@kstreeter - I have completed this PR. Please note that I had to reorganize enduserid.schema.json due to the new validation that Lars added. It should be the exact same semantics, but I would love another set of eyes on it.

**Pull request merged**
