### PR TITLE
Adding Emitted Event

### PR DESCRIPTION
**Pull request by theManikJindal**
## Author Notes
1. Adding `emitted event` to enable the transport of XDM Event Envelope compliant custom OSGI events from AEM. 
2. There's one concern though, which is that the generic nature of the `emitted` event allows for any activity to modeled as a simple `message emitted`. This, however, is a trap that the publishers of the XDM Event Envelope **must** steer away from.

@trieloff I am working on an example of this event type and will add to the PR very soon. I wanted to get the group's initial thoughts on this though, and hence, I am raising this PR.

### CODE REVIEW

**Comment by trieloff** [comment]
I agree with the concern that `emitted` is something of a black box and will make it hard to filter what exactly is happening.

Maybe one solution would be to call it `emitted-<whatevertheosgieventnameis>` so that we still have the flexibility of passing anything from OSGi to Adobe Cloud Platform, without having consumers of `emitted` events to do most of the filtering on the client-side.

I'd love to hear @fmeschbe's take on that, too.

**Comment by theManikJindal** [comment]
@trieloff see this - [XDM Event Envelope - Noun and Verb](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=AdobeCloudPlatform&title=XDM+Event+Envelope#XDMEventEnvelope-NounandVerb)

**Comment by theManikJindal** [comment]
On more thought, I think it would be agreeable to limit the range of the [`objectType`](https://github.com/adobe/xdm/blob/master/schemas/common/eventenvelope.schema.json#L15) field in the `emitted event` to certain predefined values (like an enum). 

But alas, the `objectType` may not be known to or present in XDM and thus it would be grossly limiting. But maybe that is an intended effect?!

**Comment by trieloff** [comment]
I take back what I wrote earlier: yes, we should have fewer verbs, and `objectType` gives us a way to determine, what was wrapped. Carrying OSGi events inside an `EventEnvelope` is a bit like having one envelope inside another: not unheard of, but also not super resource-effective.

**Comment by theManikJindal** [comment]
> Carrying OSGi events inside an EventEnvelope is a bit like having one envelope inside another: not unheard of, but also not super resource-effective.

So, what are you then proposing @trieloff?

**Comment by trieloff** [comment]
Not everything has to be super resource-effective, if it gets the job done and deals nicely with the constraints of established infrastructure.

**Comment by theManikJindal** [comment]
Okay, so then what I am hearing is - restrict the `objectType` to a URI that refers to an OSGI custom event, add an example, and we'd be ready to merge? :)

**Comment by trieloff** [comment]
Just add the example. objectType restriction is optional.

**Comment by theManikJindal** [comment]
@trieloff I added the example for the `emitted` event. 

However, I ran into an issue which needs consideration. The URI for a custom OSGI event was not available, and so I added the URL to its official javadoc. Let me know if this is workable or would you want something else.

**Comment by trieloff** [comment]
One minor thing: given that the description is quite long (good) put it into an external `description.md` for easier authoring.

**Comment by theManikJindal** [comment]
Thanks for reviewing @trieloff!

> OSGi topics and our event types are roughly comparable

I wasn't aware of this, is it so? Also, aren't topics custom? If so, could it give rise to situations where the `topic` name matches in two AEM repositories but they are actually different things in the real world?

**Comment by trieloff** [comment]
Yes, there is a theoretical risk of collisions, but given that OSGi is using Java's naming conventions, and it is best practice to put your domain name into the first two levels of the package name, it is quite unlikely that we will experience collision in practice.

**Comment by theManikJindal** [comment]
Done! Please review @trieloff :)

**Comment by trieloff** [comment]
Ah. I should not have merged this before I've completed the work on #23 – now I have to adjust one more schema and example.

**Pull request merged**
