### PR TITLE
Add `meta:status` of type `enum`

### PR DESCRIPTION
**Pull request by asteed**
This PR links to the issue #161 : This change is to add a new metadata type `meta:status` used to indicate the stability of the schema

### CODE REVIEW

**Comment by trieloff** [comment]
`npm run lint` does two things:
1. runs `prettier` on all JSON and MD files
2. checks if there are uncommitted changes

In 99% it‘s failing in step 2. so, just commit after running, then it should be fine.

**Comment by asteed** [comment]
Thanks @trieloff!

**Comment by asteed** [comment]
@trieloff I've added the suggested `deprecated` enum value and updated all schemas to reflect `experimental` status. Are there any other unfulfilled expectations left to address #161 or is this considered complete?

**Comment by trieloff** [comment]
Looks good!

**Pull request merged**
